version: "3.9"
services:
  web:
    build: .
    ports:
    - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
    environment: 
      - "DJANGO_SECRET_KEY=django-insecure--v%+%(&(2=4=0fok%nq8ox4#x^tctt1^lox*fdu+t(&*fjshua"
      - "DJANGO_DEBUG=False"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: